display_name_db_column_mapping = {
    # base db columns
    'base_ref_id': 'base_ref_id',
    'base_product_id': 'base_product_id',
    'Product Name': 'title',
    'Product Description - Content': 'description',
    'Business Unit': 'business_unit',
    'Sub Category': 'sub_category',
    'Sub Sub Category': 'sub_sub_category',
    'Brand': 'brand',
    'Brand Type': 'brand_type',
    'Standard Packing UOM': 'standard_packing_uom',
    'Unit Quantity UOM': 'unit_quantity_uom',
    'Purchase Price UOM': 'purchase_price_uom',
    'Unit Of Measurement - 1': 'unit_of_measurement_one',
    'Unit Of Measurement - 2': 'unit_of_measurement_two',
    'Installation - UOM': 'installation_uom',
    'Intst with Mat - UOM': 'installation_with_material_uom',
    'Classifications': 'classifications',
    'Status': 'status',
    'Category_ID': 'categoryids',
    'Key Features': 'key_features',
    'Model No.': 'model_number',
    # subscribed db columns
    'subscribed_product_id': 'subscribed_product_id',
    'Standard Packing Quantity': 'standard_packing_quantity',
    'Unit Quantity': 'quantity',
    'Installation Price': 'installation_price',
    'Installation SOW': 'installation_sow',
    'Installation with Material Price': 'installation_with_material_price',
    'Installation with Material SOW': 'installation_with_material_sow',
    'Combo/Related Products': 'combo',
    'Variant On': 'variant_on',
    # store price mapping
    'Store Id': 'store_id',
    'Pincode Mapping': 'region_id',
    'Price Type': 'price_type',
    'Price (MRP/LP)': 'store_price',
    'Discount': 'discount',
    'Purchase Price': 'purchase_price',
    'Markup': 'markup',
    'Offer Price': 'store_offer_price',
    'MOQ Retail': 'moq_retail',
    'MOQ Increment Retail': 'moq_incremental_retail',
    'MOQ Enterprise': 'moq_enterprise',
    'MOQ Increment Enterprise': 'moq_increment_enterprise',
    'Dispatch Location': 'dispatch_location',
    'VAT': 'vat',
    'Shipping Charge': 'shipping_charge',
    'Stock Status': 'stock_status',
    'Price Validity': 'price_validity',
    'Shipment Mode': 'shipment_mode',
    'Is_Cancelable': 'is_cancelable',
    'Is_Cod': 'is_cod',
    'Is_Returnable': 'is_returnable',
    'Processing_Time': 'processing_time',
    'Conforming Standard': 'conforming_standard',
    'Warranty': 'warranty',
    'Item Buying Type': 'item_buying_type',
    'Publish': 'publish',
}
